name: Deploy Containerized App with Nginx
on:
  push:
    branches:
      - main  

jobs:
  configure:
    name: Configure EC2 with Ansible
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: bash ansible.sh  

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          # This command successfully creates ~/.ssh/us-connect.pem
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/us-connect.pem
          chmod 600 ~/.ssh/deploy.pem

      - name: Run Ansible Playbook
        # We need to disable host key checking in the workflow env for this to connect easily
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          # This command now works because the inventory file path matches the created key path
          ansible-playbook -i inventory.ini setup-server.yml    

  build-and-deploy:
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    needs: configure

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

       # --- ADD THIS STEP ---
      - name: Copy source code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.80.80.83 # Your EC2 IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "node-ec2-app" # The current directory on the runner (your repo root)
          target: "/home/ubuntu/deploy-nodeapp-with-nginx" # The destination directory on the EC2
      # ---------------------

      - name: Deploy Container via SSH
        uses: appleboy/ssh-action@v1.0.7 #Third-party GitHub Action designed to easily run SSH commands on a remote server within your automated workflow
        with:
          host: 3.80.80.83 # Replace with your actual IP or a variable
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/deploy-nodeapp-with-nginx/node-ec2-app # Navigate to home directory on EC2
            # Use SCP previously or make sure code is there
            # Build the image remotely on the EC2 instance
            docker build -t node-nginx-app:latest .
            docker run -d -p 3000:3000 --name node-app --restart unless-stopped node-nginx-app:latest
            sleep 5
            docker ps -a # Verify remotely
            echo "✅ Deployment complete!"
